name: GitHub Action Project 

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: ec2-user 
          key : ${{secrets.SSH_KEY}}
          script: |
            cd /home/ec2-user/GitHubAction
            git pull 
            docker ps
            docker stop app02
            docker rm app02
            docker rmi app02
            docker build -t app02 .
            docker run -d --name app02 -p 80:80 app02

